name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest -v

      - name: Run test coverage
        run: uv run pytest --cov=src

      - name: Run ruff
        run: uv run ruff check .